name: Delete branch when PR is closed
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "2 * * * *"

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
