---
name: "Lambda with Layer Deployment Action"

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      function_name:
        required: true
        type: string
      s3_bucket:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # specify your desired Python version

      - name: Create Function Artifacts
        run: |
          sudo apt-get install zip -y
          zip -r main.zip ./handler.py
          aws s3 cp main.zip s3://${{ inputs.s3_bucket }}/lambda/${{ inputs.function_name }}.zip

      - name: Upload Function
        run: |
          aws lambda update-function-code --function-name ${{ inputs.function_name }} --zip-file fileb://handler.zip --publish --region ${{ inputs.aws_region }}

      - name: Create Layer Artifacts
        run: |
          pipenv install --deploy --ignore-pipfile
          pipenv lock -r > requirements.txt
          pip install -r requirements.txt -t layer
          zip -r layer.zip layer

      - name: Push Layer
        run: |
          aws lambda publish-layer-version --layer-name ${{ inputs.function_name }}-py --zip-file fileb://layer.zip --compatible-runtimes python3.11

      - name: Update Layer Version
        run: |
          latest_version=$(aws lambda list-layer-versions --layer-name ${{ inputs.function_name }}-py --query 'max_by(LayerVersions, &Version).Version')
          aws lambda update-function-configuration --function-name ${{ inputs.function_name }} --layers arn:aws:lambda:${{ inputs.aws_region }}:${{ secrets.aws_account_id }}:layer:${{ inputs.function_name }}-py:${latest_version}
