---
name: "ECS Deployment Action"

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      ecs_cluster:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string
      task_family:
        required: true
        type: string
      ecs_service:
        required: true
        type: string
      envs_list:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      secret_config_key:
        required: true
        type: string
      internal_service_host:
        required: true
        type: string
      sentry_project:
        required: true
        type: string
      sentry_org:
        required: true
        type: string

jobs:
  run:
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.env_name }}
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --file ${{ inputs.dockerfile_path }} -t $ECR_REGISTRY/${{ inputs.ecr_repository }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ inputs.ecr_repository }}:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/${{ inputs.ecr_repository }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ inputs.task_family }} --query taskDefinition > task-definition.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Fill in the new image ID in the Amazon ECS task definition
        run: python ../../ecs_task_def_json.py task-definition.json ${{ steps.build-image.outputs.image }} '[{"SERVICE_ENV": "${{ inputs.env_name }}"}, {"AWS_REGION": "${{ inputs.aws_region }}"}, {"SECRET_CONFIG_KEY": "${{ inputs.secret_config_key }}"}, {"INTERNAL_SERVICE_HOST": "${{ inputs.internal_service_host }}"}]'

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: ${{ inputs.ecs_service }}
          cluster: ${{ inputs.ecs_cluster }}

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_RELEASE_TOKEN }}
          SENTRY_ORG: ${{ inputs.sentry_org }}
          SENTRY_PROJECT: ${{ inputs.sentry_project }}
        with:
          environment: ${{ inputs.env_name }}
