name: "ECS Deployment Action"

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      ecs_cluster:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string
      task_family:
        required: true
        type: string
      ecs_service:
        required: true
        type: string
      container_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string

    secrets:
      assume_role_arn:
        required: true

jobs:        
  zap_scan:
    runs-on: ubuntu-latest
    env:
      FRONTEND_URL: https://dev-omni.crego.tech
      BACKEND_URL: https://dev-omni-api.crego.tech
      ZAP_IMAGE: ghcr.io/zaproxy/zaproxy:stable
      ZAP_PORT: "8080"

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create reports directory
        run: mkdir -p zap-reports && chmod 777 zap-reports

      - name: "Run ZAP Scan on Frontend"
        run: |
          docker run \
            -v $(pwd)/zap-reports:/zap/wrk/:rw \
            -e ZAP_PORT=$ZAP_PORT \
            -u zap \
            -p $ZAP_PORT:$ZAP_PORT \
            --rm $ZAP_IMAGE zap-baseline.py \
            -t $FRONTEND_URL \
            -r /zap/wrk/frontend-report.html \
            -x /zap/wrk/frontend-report.xml \
            -d

      - name: "Run ZAP Scan on Backend"
        run: |
          docker run \
            -v $(pwd)/zap-reports:/zap/wrk/:rw \
            -e ZAP_PORT=$ZAP_PORT \
            -u zap \
            -p $ZAP_PORT:$ZAP_PORT \
            --rm $ZAP_IMAGE zap-baseline.py \
            -t $BACKEND_URL \
            -r /zap/wrk/backend-report.html \
            -x /zap/wrk/backend-report.xml \
            -d

      - name: "Upload ZAP Reports"
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-reports-${{ github.run_id }}
          path: zap-reports/*.html zap-reports/*.xml