---
name: "Web Deployment Action"

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      bucket_name:
        required: true
        type: string
      api_endpoint:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Clean Cache
        run: npm cache clean --force

      - name: Build project
        env:
          VITE_API_URL: ${{ inputs.api_endpoint }}
        run: npm run build

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::563577067739:role/Github-crego-omni-assume-role
          aws-region: ap-south-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/ s3://${{ inputs.bucket_name }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} \
            --paths "/*"
